### ISSUE TITLE
Bad quotes on profile

### ISSUE THREAD

**Issue by saviomartin** [siddharth2016/quote-readme#1]
Hey @siddharth2016

thanks for your attention on this. I thought this is a good feature to be used in my profile but certain bad quotes are ruining my please, and make others feel insecure about me. This is really bad to use such words. I really hate this now.  

![](https://user-images.githubusercontent.com/61895712/107773663-fd12f500-6d63-11eb-9d03-1ba0c34fbebb.png)

Hope you take action on this.
**Savio Martin**

**Comment by siddharth2016** [comment]
Hey Savio,

Really sorry you had to go through this. All the quotes and facts are being scraped from internet and it is somewhat out of my control to actually control what is written over there !

You can alternatively specify `OPTION: both            # default - both, can be one of (quote, funfact, both), if 'both' then will display either a quote or a fact` parameter in your YAML workflow file. Simply change it to `quote`.

Still, I thank you for pointing this out, I have removed this from stored quotes/facts sheet and it should not come to display anymore.

Feel free to star/unstar the repo, it was made purely as a learning activity, never meant to hurt any sentiment.

Find the scripts used to scrape the quotes/facts [quotes-here](https://blog.codekaro.info/scraping-web-inspiring-quotes) and [facts-here](https://blog.codekaro.info/scraping-web-awesome-facts).

Thank you and all the best for your future endeavours !
Siddharth Chandra

**Comment by siddharth2016** [comment]
I am closing this issue, I hope my response helps you out and thank you for taking your time out for this not-so-useful github action !

Namaste 🙏
Siddharth Chandra
