### ISSUE TITLE
Custom quotes/fun fact

### ISSUE THREAD

**Issue by APratham** [siddharth2016/quote-readme#2]
Is it possible for me to use your GitHub action with my own list of quotes/fun facts? Also why is it blue? Black is good enough I think

**Comment by APratham** [comment]
I figured out about the custom facts.. but still wondering how to do this without the blue colour. Like if you want just the text simply.

**Comment by siddharth2016** [comment]
Hi Pratham

Blue color is because it is taking it as a link, below is one such example

```

<a href="https://github.com/marketplace/actions/quote-readme">
<!--STARTS_HERE_QUOTE_README-->
<i>❝Windows doesn’t allow for creation of folders tagged CON, PRN, AUX, or NUL. These are keywords reserved by DOS.❞</i>
<!--ENDS_HERE_QUOTE_README-->
</a>

```

If you remove `<a>...</a>` tags then blue color should not come.

```
<!--STARTS_HERE_QUOTE_README-->
<i>❝Windows doesn’t allow for creation of folders tagged CON, PRN, AUX, or NUL. These are keywords reserved by DOS.❞</i>
<!--ENDS_HERE_QUOTE_README-->
```

Let me know if this helps, thanks.

**Comment by siddharth2016** [comment]
> Is it possible for me to use your GitHub action with my own list of quotes/fun facts? Also why is it blue? Black is good enough I think

For custom facts and quotes, I am working on that, there is something similar I did for [update-image-readme](https://github.com/marketplace/actions/update-image-readme), I will be extending this same functionality for quote-readme action as well. Please wait till April end, been busy with office work lately.

**Comment by APratham** [comment]
@siddharth2016 I am facing an error if possible please help: https://github.com/APratham/APratham/runs/2163640664

![image](https://user-images.githubusercontent.com/33273990/111958002-bc508d80-8b12-11eb-9fc2-ebcf6c448e87.png)

**Comment by siddharth2016** [comment]
`text_list` seems to be empty, please check if the code is able to access the folder/files and a list of facts is getting created.


EDIT:
Are you trying to access your own facts/quotes, from your repository?

If that is the case then surely, code from my repo would not be able to access something from your repo, I need to add that function in main.py

EDIT 2:

I saw your profile readme, it seems like the action work now? How did you manage to resolve this? It would be helpful if you could contribute to README.md with your error and how did you resolve it, for other new users.

**Comment by APratham** [comment]
@siddharth2016 I have been experimenting with a lot of things, and although as you can see that I have been able to make it work, it really isn't what I wanted. 

What I really wanted was to replace the ⚡ Fun fact: Marvel's first family... line with auto updating facts. So I am trying out various solutions to accomplish that

Also I can add it to the documentation but it really was just a silly typo, I am not sure how many will be interested in reading about that 😂😂

**Comment by siddharth2016** [comment]
ahh, okay 😂😂

No issues, I will be closing this ticket then if nothing else is creating any error. Please create a PR when you accomplish your desired change, I will see how I can merge it with the current one.

Thanks again for reaching out, cheers!
