### ISSUE TITLE
Your Site Might Be Hacked

### ISSUE THREAD

**Issue by lulu-cao** [siddharth2016/quote-readme#3]
Hello, I'm randomly browsing GitHub Actions resources and found your repo. When I click on "here" in "There is a short tutorial with enough steps for you to get started with this not-so-useful GitHub Action. Check that out here", the link always directs me to a random purchase website that is not intended for your GitHub action. I'm thinking you might be hacked or there might be glitches somewhere. Thanks for your attention.

**Comment by siddharth2016** [comment]
Hi @lulu-cao 
First of all, the issue title scared the hell out of me!!
And, thanks a lot for bringing this to my attention, I have migrated my blogs to a different domain, I will update those ASAP.

In the mean time, you can check the article here:
https://chandraji.dev/quote-readme-see-wonderful-quotesfun-facts-on-your-github-profile-readme

**Comment by siddharth2016** [comment]
updated the links. Thanks!
