### ISSUE TITLE
GitHub Action Workflow failed to run

### ISSUE THREAD

**Issue by jaborjkath** [siddharth2016/quote-readme#4]
Hello @siddharth2016 , I am a newbie in GitHub Community. Really finding your resources so helpful. By the way, I tried to set this and executed on my Profile Repository. My workflow failed to run. In my profile repository > Actions, error details look like this:
![Update Quote README - failed to run](https://github.com/siddharth2016/quote-readme/assets/143686495/a308d4d9-c40f-4aca-ac9c-8eb4338a9976)  Have I missed a step here?

I was able to find a workaround for the issue using this solution [here](https://stackoverflow.com/a/77167633). 
To enable **read and write permissions** from the relevant repository settings (top right corner) → Actions (left navigation bar) → General → Workflow permissions section. Just sharing this especially to new users. 

Thanks for your attention.

**Comment by siddharth2016** [comment]
Hi @jaborjkath, is your workflow working fine now? After doing the workaround as stated in Stackoverflow post?

**Comment by jaborjkath** [comment]
Hi @siddharth2016, yes my workflow is working fine now using the workaround from the Stackoverflow post. Thanks for checking on this one.

**Comment by siddharth2016** [comment]
> Hi @siddharth2016, yes my workflow is working fine now using the workaround from the Stackoverflow post. Thanks for checking on this one.

Nice, I will add this info to the README.md as well. Thank you for using this GitHub Action! @jaborjkath

**Comment by jaborjkath** [comment]
Thanks also for noticing. That'd be great! Have a prosperous brand new year ahead, @siddharth2016. Cheers! 🙏🏼

**Comment by siddharth2016** [comment]
Happy New Year!
Sorry, I got late in replying to your issue, was busy with office work. Thanks again, @jaborjkath.

**Comment by jaborjkath** [comment]
Aah, no worries @siddharth2016. Happy New Year! Hope all is well with you.

**Comment by siddharth2016** [comment]
> Aah, no worries @siddharth2016. Happy New Year! Hope all is well with you.

Yep, thanks for asking! Wishing you a wonderful year ahead. Here's to new learnings, experiences and to lots of fun 🍻

**Comment by jaborjkath** [comment]
Really appreciate your well wishes @siddharth2016 🙏🏼 Cheers! Indeed, looking forward also to new learnings, new beginnings, and yes, to really having lots of fun.🍻
